# ROV server configuration
server:
  host: "0.0.0.0"
  port: 5000
  debug: false
  secret_key: "your-secret-key-change-this-in-production"

# Video configuration
video:
  # Video source: 'camera', 'url', 'dummy'
  source: "camera"
  
  # Video stream URL (for source: 'url')
  stream_url: "rtsp://192.168.1.100:554/stream"
  
  # Local camera index (for source: 'camera')
  camera_index: 0
  
  # Quality configuration
  fps: 30
  stream_fps: 15
  jpeg_quality: 70
  
  # Resolution (width, height) - leave null for auto
  resolution: [640, 480]

# System configuration
system:
  # Sensor simulation
  simulate_sensors: true
  
  # Real WiFi detection (for Raspberry Pi)
  detect_real_wifi: true
  
  # Update intervals (seconds)
  sensor_update_interval: 5.0
  log_cleanup_interval: 300  # 5 minutes
  
  # Log limits
  max_logs: 100
  
  # Initial values
  initial_wifi_strength: 85
  initial_battery: 67

# Controls configuration
controls:
  # Joystick
  joystick:
    max_radius: 55
    deadzone: 0.05
  
  # Depth slider
  depth:
    min_value: 0
    max_value: 100
    initial_value: 0
  
  # Other controls
  light_initial_state: false

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Network configuration
network:
  cors_allowed_origins: "*"
  socketio_async_mode: "threading"
  
# Advanced configuration
advanced:
  # Camera connection timeout
  camera_timeout: 5.0
  
  # Connection retries
  camera_retry_attempts: 3
  
  # Video frame buffer
  frame_buffer_size: 2